spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.H2Dialect
  flyway:
    enabled: true
    locations: classpath:db
  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    org:
      flywaydb: info
      springframework:
        jdbc: debug
